name: CI/CD Pipeline del Taller

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  run-ci-on-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Comentar en el PR (Iniciando)
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **ü§ñ CI/CD en acci√≥n. Ejecutando tareas...**

      - name: 2. Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: 3. Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 4. Instalar dependencias del Backend
        run: pip install -r backend/requirements.txt

      - name: 5. Correr Pruebas Unitarias (Pytest)
        run: python -m pytest backend/test_main.py

      - name: 6. Comentar en el PR (√âxito)
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **‚úÖ CI/CD terminado con √©xito.**

      - name: 7. Comentar en el PR (Fallo)
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **‚ùå CI/CD fallido. Revisa los logs.**

  build-and-publish-on-main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: 2. Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias del Backend
        run: pip install -r backend/requirements.txt

      - name: 4. Correr Pruebas Unitarias (Verificaci√≥n final)
        run: python -m pytest backend/test_main.py

      - name: 5. Iniciar sesi√≥n en GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 6. Construir y Publicar imagen del Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:latest

      - name: 7. Construir y Publicar imagen del Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest